[pytest]
markers =
    smoke: быстрые тесты
    regression: регрессионные тесты
    slow: медленные тесты
    api: API-тесты
    ui: UI-тесты
    db: Тесты баз данных
log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_data_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_forman=%Y-%m-%d %H:%M:%S